# Generated by Django 3.1 on 2021-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reserv_bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_dash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_etc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pm_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xmr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='РИПЛ'),
        ),
    ]
