# Generated by Django 3.1 on 2021-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210108_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reserv_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ЮМАНИ'),
        ),
    ]
