# Generated by Django 3.1 on 2021-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210118_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verifications_level_one',
            field=models.BooleanField(default=False, verbose_name='Верификация уровень 1'),
        ),
    ]
