# Generated by Django 3.1 on 2021-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_verifications_level_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_in_roketbank_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='active_out_roketbank_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comis_in_roketbank_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comis_out_roketbank_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='requsites_roketbank_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reserv_roketbank_rub',
        ),
    ]
