# Generated by Django 3.1 on 2021-02-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rangesumdeposit_rangesumwidth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangesumwidth',
            options={'verbose_name': 'Диапазон для вывода', 'verbose_name_plural': 'Диапазон для вывода'},
        ),
    ]
