# Generated by Django 3.1 on 2021-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210201_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_dash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_etc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_pm_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_xmr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='РИПЛ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_dash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_etc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_pm_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_xmr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='РИПЛ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_dash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_etc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_pm_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_xmr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='РИПЛ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_dash',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_etc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_pm_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_xmr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='РИПЛ'),
        ),
    ]
