# Generated by Django 3.1 on 2021-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210203_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Логин пользователя'),
        ),
    ]
