# Generated by Django 3.1 on 2021-02-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210203_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_Email_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_key', models.CharField(db_index=True, max_length=150, verbose_name='Ключ')),
                ('confirm_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('confirm_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
    ]
