# Generated by Django 3.1 on 2021-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_confirm_email_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_email_key',
            name='confirm_username',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Пользователь'),
        ),
    ]
