# Generated by Django 3.1 on 2021-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210209_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_email_key',
            name='confirm_key',
            field=models.CharField(max_length=150, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='confirm_email_key',
            name='confirm_username',
            field=models.CharField(max_length=150, verbose_name='Пользователь'),
        ),
    ]
