# Generated by Django 3.1 on 2021-02-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210210_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_program',
            name='line_onefielsd',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='onefielsd', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1'),
        ),
        migrations.AlterField(
            model_name='line_program',
            name='line_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
