# Generated by Django 3.1 on 2021-02-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210210_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line_program',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.RemoveField(
            model_name='line_program',
            name='line_onefielsd',
        ),
        migrations.AlterField(
            model_name='line_program',
            name='line_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
