# Generated by Django 3.1 on 2020-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200827_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='баланс'),
        ),
    ]
