# Generated by Django 3.1 on 2021-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210211_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_program',
            name='line_ref_code',
            field=models.CharField(default=0, max_length=50, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='line_program',
            name='line_ref_link',
            field=models.URLField(verbose_name='Реферальная ссылка'),
        ),
    ]
