# Generated by Django 3.1 on 2020-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200827_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='баланс'),
        ),
    ]
