# Generated by Django 3.1 on 2020-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200827_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='баланс'),
        ),
    ]
