# Generated by Django 3.1 on 2021-02-12 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210211_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_program',
            name='date_joined_ref',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации партнера'),
        ),
        migrations.AddField(
            model_name='line_program',
            name='fio_ref',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='line_program',
            name='profit_ref',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Доход от партнера'),
        ),
        migrations.AlterField(
            model_name='line_program',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.line_program', verbose_name='Родитель'),
        ),
    ]
