# Generated by Django 3.1 on 2021-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210212_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_program',
            name='fio_ref',
            field=models.CharField(max_length=250, null=True, verbose_name='ФИО'),
        ),
    ]
