# Generated by Django 3.1 on 2021-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210212_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_program',
            name='fio_ref',
            field=models.CharField(default='-', max_length=250, verbose_name='ФИО'),
        ),
    ]
