# Generated by Django 3.1 on 2020-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200827_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20, verbose_name='баланс'),
        ),
    ]
