# Generated by Django 3.1 on 2020-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200827_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='баланс'),
        ),
    ]
