# Generated by Django 3.1 on 2021-02-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210214_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_program',
            name='date_joined_ref',
        ),
        migrations.RemoveField(
            model_name='line_program',
            name='fio_ref',
        ),
        migrations.RemoveField(
            model_name='line_program',
            name='profit_ref',
        ),
    ]
