# Generated by Django 3.1 on 2021-02-14 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210214_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit_Partner_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_day_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('profit_day_partner', models.CharField(max_length=150, verbose_name='Партнер')),
                ('profit_day_parent', models.CharField(max_length=150, verbose_name='Родитель')),
                ('profit_day_sum', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Сумма')),
                ('profit_day_level', models.CharField(max_length=150, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
            },
        ),
        migrations.CreateModel(
            name='Profit_Partner_Good_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_good_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('profit_good_user', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('profit_good_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Итоговое начисление',
                'verbose_name_plural': 'Итоговые начисления',
            },
        ),
    ]
