# Generated by Django 3.1 on 2020-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200827_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='баланс'),
        ),
    ]
