# Generated by Django 3.1 on 2021-02-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_profit_partner_good_day_profit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit_partner_good_day',
            name='profit_status',
        ),
    ]
