# Generated by Django 3.1 on 2021-02-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_profit_partner_good_day_profit_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit_partner_day',
            options={'verbose_name': 'Ожидают начисления', 'verbose_name_plural': 'Ожидающие начисления'},
        ),
        migrations.AlterModelOptions(
            name='profit_partner_good_day',
            options={'verbose_name': 'Проведенное начисление', 'verbose_name_plural': 'Проведенные начисления'},
        ),
        migrations.AddField(
            model_name='profit_partner_day',
            name='profit_day_status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
