# Generated by Django 3.1 on 2021-02-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210216_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_program',
            name='line_ref_date',
        ),
    ]
