# Generated by Django 3.1 on 2021-02-16 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_line_program_line_ref_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_program',
            name='line_ref_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 17, 39, 45, 122079, tzinfo=utc), max_length=50, verbose_name='Дата регистрации'),
        ),
    ]
