# Generated by Django 3.1 on 2021-02-18 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_line_program_line_ref_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_program',
            name='line_ref_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=50, verbose_name='Дата регистрации'),
        ),
    ]
