# Generated by Django 3.1 on 2021-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210218_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_alfabank_rub',
            field=models.IntegerField(default=0, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_gazprombank_rub',
            field=models.IntegerField(default=0, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_mtsbank_rub',
            field=models.IntegerField(default=0, verbose_name='МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_otkritie_rub',
            field=models.IntegerField(default=0, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_payeer_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_payeer_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_payeer_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_paypal_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_paypal_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_paypal_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_pm_eur',
            field=models.IntegerField(default=0, verbose_name='ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_pm_usd',
            field=models.IntegerField(default=0, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_pochtabank_rub',
            field=models.IntegerField(default=0, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_psb_rub',
            field=models.IntegerField(default=0, verbose_name='ПСБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_qiwi_rub',
            field=models.IntegerField(default=0, verbose_name='КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_qiwi_usd',
            field=models.IntegerField(default=0, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_raifaizen_rub',
            field=models.IntegerField(default=0, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_rnkb_rub',
            field=models.IntegerField(default=0, verbose_name='РНКБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_rosbank_rub',
            field=models.IntegerField(default=0, verbose_name='РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_rosselhoz_rub',
            field=models.IntegerField(default=0, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_russtandart_rub',
            field=models.IntegerField(default=0, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_sberbank_rub',
            field=models.IntegerField(default=0, verbose_name='СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_skrill_eur',
            field=models.IntegerField(default=0, verbose_name='СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_skrill_usd',
            field=models.IntegerField(default=0, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_tinkoff_rub',
            field=models.IntegerField(default=0, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_umoney_rub',
            field=models.IntegerField(default=0, verbose_name='ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_vtb_rub',
            field=models.IntegerField(default=0, verbose_name='ВТБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_webmoney_eur',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_webmoney_rub',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_max_webmoney_usd',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_alfabank_rub',
            field=models.IntegerField(default=0, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_gazprombank_rub',
            field=models.IntegerField(default=0, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_mtsbank_rub',
            field=models.IntegerField(default=0, verbose_name='МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_otkritie_rub',
            field=models.IntegerField(default=0, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_payeer_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_payeer_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_payeer_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_paypal_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_paypal_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_paypal_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_pm_eur',
            field=models.IntegerField(default=0, verbose_name='ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_pm_usd',
            field=models.IntegerField(default=0, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_pochtabank_rub',
            field=models.IntegerField(default=0, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_psb_rub',
            field=models.IntegerField(default=0, verbose_name='ПСБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_qiwi_rub',
            field=models.IntegerField(default=0, verbose_name='КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_qiwi_usd',
            field=models.IntegerField(default=0, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_raifaizen_rub',
            field=models.IntegerField(default=0, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_rnkb_rub',
            field=models.IntegerField(default=0, verbose_name='РНКБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_rosbank_rub',
            field=models.IntegerField(default=0, verbose_name='РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_rosselhoz_rub',
            field=models.IntegerField(default=0, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_russtandart_rub',
            field=models.IntegerField(default=0, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_sberbank_rub',
            field=models.IntegerField(default=0, verbose_name='СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_skrill_eur',
            field=models.IntegerField(default=0, verbose_name='СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_skrill_usd',
            field=models.IntegerField(default=0, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_tinkoff_rub',
            field=models.IntegerField(default=0, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_umoney_rub',
            field=models.IntegerField(default=0, verbose_name='ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_vtb_rub',
            field=models.IntegerField(default=0, verbose_name='ВТБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_webmoney_eur',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_webmoney_rub',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumdeposit',
            name='deposit_min_webmoney_usd',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_alfabank_rub',
            field=models.IntegerField(default=0, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_gazprombank_rub',
            field=models.IntegerField(default=0, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_mtsbank_rub',
            field=models.IntegerField(default=0, verbose_name='МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_otkritie_rub',
            field=models.IntegerField(default=0, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_payeer_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_payeer_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_payeer_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_paypal_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_paypal_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_paypal_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_pm_eur',
            field=models.IntegerField(default=0, verbose_name='ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_pm_usd',
            field=models.IntegerField(default=0, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_pochtabank_rub',
            field=models.IntegerField(default=0, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_psb_rub',
            field=models.IntegerField(default=0, verbose_name='ПСБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_qiwi_rub',
            field=models.IntegerField(default=0, verbose_name='КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_qiwi_usd',
            field=models.IntegerField(default=0, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_raifaizen_rub',
            field=models.IntegerField(default=0, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_rnkb_rub',
            field=models.IntegerField(default=0, verbose_name='РНКБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_rosbank_rub',
            field=models.IntegerField(default=0, verbose_name='РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_rosselhoz_rub',
            field=models.IntegerField(default=0, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_russtandart_rub',
            field=models.IntegerField(default=0, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_sberbank_rub',
            field=models.IntegerField(default=0, verbose_name='СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_skrill_eur',
            field=models.IntegerField(default=0, verbose_name='СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_skrill_usd',
            field=models.IntegerField(default=0, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_tinkoff_rub',
            field=models.IntegerField(default=0, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_umoney_rub',
            field=models.IntegerField(default=0, verbose_name='ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_vtb_rub',
            field=models.IntegerField(default=0, verbose_name='ВТБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_webmoney_eur',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_webmoney_rub',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_max_webmoney_usd',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_alfabank_rub',
            field=models.IntegerField(default=0, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_gazprombank_rub',
            field=models.IntegerField(default=0, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_mtsbank_rub',
            field=models.IntegerField(default=0, verbose_name='МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_otkritie_rub',
            field=models.IntegerField(default=0, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_payeer_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_payeer_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_payeer_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_paypal_eur',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_paypal_rub',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_paypal_usd',
            field=models.IntegerField(default=0, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_pm_eur',
            field=models.IntegerField(default=0, verbose_name='ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_pm_usd',
            field=models.IntegerField(default=0, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_pochtabank_rub',
            field=models.IntegerField(default=0, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_psb_rub',
            field=models.IntegerField(default=0, verbose_name='ПСБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_qiwi_rub',
            field=models.IntegerField(default=0, verbose_name='КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_qiwi_usd',
            field=models.IntegerField(default=0, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_raifaizen_rub',
            field=models.IntegerField(default=0, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_rnkb_rub',
            field=models.IntegerField(default=0, verbose_name='РНКБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_rosbank_rub',
            field=models.IntegerField(default=0, verbose_name='РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_rosselhoz_rub',
            field=models.IntegerField(default=0, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_russtandart_rub',
            field=models.IntegerField(default=0, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_sberbank_rub',
            field=models.IntegerField(default=0, verbose_name='СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_skrill_eur',
            field=models.IntegerField(default=0, verbose_name='СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_skrill_usd',
            field=models.IntegerField(default=0, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_tinkoff_rub',
            field=models.IntegerField(default=0, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_umoney_rub',
            field=models.IntegerField(default=0, verbose_name='ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_vtb_rub',
            field=models.IntegerField(default=0, verbose_name='ВТБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_webmoney_eur',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_webmoney_rub',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='rangesumwidth',
            name='width_min_webmoney_usd',
            field=models.IntegerField(default=0, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
    ]
