# Generated by Django 3.1 on 2020-08-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance2',
            field=models.FloatField(default=0, verbose_name='баланс2'),
        ),
    ]
