# Generated by Django 3.1 on 2021-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210220_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='requsites_alfabank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_bch',
            field=models.CharField(default='-', max_length=50, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_btc',
            field=models.CharField(default='-', max_length=50, verbose_name='БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_dash',
            field=models.CharField(default='-', max_length=50, verbose_name='ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_etc',
            field=models.CharField(default='-', max_length=50, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_eth',
            field=models.CharField(default='-', max_length=50, verbose_name='ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_gazprombank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_ltc',
            field=models.CharField(default='-', max_length=50, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_mtsbank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_otkritie_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_eur',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_eur',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_btc',
            field=models.CharField(default='-', max_length=50, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_eur',
            field=models.CharField(default='-', max_length=50, verbose_name='ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pochtabank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_psb_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_qiwi_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_qiwi_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_raifaizen_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rnkb_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rosbank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rosselhoz_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_russtandart_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_sberbank_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_skrill_eur',
            field=models.CharField(default='-', max_length=50, verbose_name='СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_skrill_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_tinkoff_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_umoney_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_vtb_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_eur',
            field=models.CharField(default='-', max_length=50, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_rub',
            field=models.CharField(default='-', max_length=50, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_usd',
            field=models.CharField(default='-', max_length=50, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_xmr',
            field=models.CharField(default='-', max_length=50, verbose_name='МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_xrp',
            field=models.CharField(default='-', max_length=50, verbose_name='РИПЛ'),
        ),
    ]
