# Generated by Django 3.1 on 2020-08-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_customuser_balance2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance2',
        ),
    ]
