# Generated by Django 3.1 on 2020-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_customuser_balance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance2',
            field=models.FloatField(default=0.0, verbose_name='баланс2'),
        ),
    ]
