# Generated by Django 3.1 on 2021-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210220_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Холд $'),
        ),
    ]
