# Generated by Django 3.1 on 2020-09-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200904_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.customuserid', verbose_name='Категория пользователя'),
        ),
    ]
