# Generated by Django 3.1 on 2020-09-10 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20200904_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserid',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balancebtc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Баланс BTC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balancerub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс RUB'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balanceusd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс USD'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kompan_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс общий'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customuserid', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин пользователя'),
        ),
        migrations.AlterField(
            model_name='customuserid',
            name='custuserid',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Роль'),
        ),
    ]
