# Generated by Django 3.1 on 2020-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20200910_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_user', models.CharField(max_length=150, verbose_name='Тразакция пользователя')),
                ('transaction_name', models.CharField(max_length=150, verbose_name='Название транзакции')),
                ('transaction_status', models.CharField(max_length=50, verbose_name='Статус')),
                ('transaction_currency', models.CharField(max_length=30, verbose_name='Валюта')),
                ('transaction_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user/', verbose_name=''),
        ),
    ]
