# Generated by Django 3.1 on 2020-09-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200910_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
