# Generated by Django 3.1 on 2020-09-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balancebtc',
        ),
    ]
