# Generated by Django 3.1 on 2020-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_customuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
    ]
