# Generated by Django 3.1 on 2020-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_customuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balanceeur',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balancerub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balanceusd',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс $'),
        ),
    ]
