# Generated by Django 3.1 on 2020-09-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20200916_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='valute_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен EUR'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valute_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен RUB'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valute_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен USD'),
        ),
    ]
