# Generated by Django 3.1 on 2020-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20200920_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='valute_with_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на вывод EUR'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valute_with_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на вывод RUB'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valute_with_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на вывод USD'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='valute_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на пополнение EUR'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='valute_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на пополнение RUB'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='valute_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на пополнение USD'),
        ),
    ]
