# Generated by Django 3.1 on 2020-12-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20201218_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='requsites_qiwi',
        ),
    ]
