# Generated by Django 3.1 on 2020-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20201218_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='valute_eur',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='valute_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='valute_usd',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='valute_with_eur',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='valute_with_rub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='valute_with_usd',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_alfabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='БИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ДАШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЭФИР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_gazprombank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_mtsbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='МТСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_otkritie_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_payeer_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_payeer_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_payeer_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_paypal_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_paypal_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_paypal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_pm_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_pm_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_pochtabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_psb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПСБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_qiwi_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КИВИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_qiwi_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_raifaizen_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_rnkb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РНКБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_roketbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОКЕТБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_rosbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_rosselhoz_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_russtandart_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_sberbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СБЕРБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_skrill_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СКРИЛЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_skrill_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_tinkoff_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЮМАНИ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_vtb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=50, verbose_name='ВТБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_webmoney_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_webmoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_webmoney_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='МОНЕРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_in_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РИПЛ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_alfabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='АЛЬФАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='БИТКОИНКЕШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='БИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ДАШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЭФИРКЛАССИК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЭФИР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_gazprombank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ГАЗПРОМБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЛАЙТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_mtsbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='МТСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_otkritie_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ОТКРЫТИЕ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_payeer_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_payeer_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_payeer_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЕЕРДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_paypal_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_paypal_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_paypal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМБИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_pm_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_pm_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПМДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_pochtabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПОЧТАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_psb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ПСБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_qiwi_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КИВИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_qiwi_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КИВИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_raifaizen_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_rnkb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РНКБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_roketbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОКЕТБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_rosbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_rosselhoz_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_russtandart_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РУССКИЙСТАНДАРТ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_sberbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СБЕРБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_skrill_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СКРИЛЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_skrill_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='СКРИЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_tinkoff_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ТИНЬКОФФ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ЮМАНИ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_vtb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=50, verbose_name='ВТБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_webmoney_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_webmoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_webmoney_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='МОНЕРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comis_out_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РИПЛ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_change',
            field=models.BooleanField(default=False, verbose_name='Статус активности обработчика'),
        ),
    ]
