# Generated by Django 3.1 on 2020-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20201224_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_in_alfabank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ АЛЬФАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_bch',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ БИТКОИНКЕШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_btc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ БИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_dash',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ДАШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_etc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ЭФИРКЛАССИК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_eth',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ЭФИР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_gazprombank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ГАЗПРОМБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_ltc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ЛАЙТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_mtsbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ МТСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_otkritie_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ОТКРЫТИЕ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_payeer_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЕЕРЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_payeer_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЕЕРРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_payeer_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЕЕРДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_paypal_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЙПАЛЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_paypal_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЙПАЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_paypal_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_pm_btc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПМБИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_pm_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПМЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_pm_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПМДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_pochtabank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПОЧТАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_psb_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ПСБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_qiwi_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ КИВИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_qiwi_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ КИВИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_raifaizen_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_rnkb_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РНКБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_roketbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РОКЕТБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_rosbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РОСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_rosselhoz_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_russtandart_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РУССКИЙСТАНДАРТ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_sberbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ СБЕРБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_skrill_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ СКРИЛЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_skrill_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ СКРИЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_tinkoff_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ТИНЬКОФФ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_umoney_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ЮМАНИ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_vtb_rub',
            field=models.BooleanField(default=False, max_length=50, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ВТБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_webmoney_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ВЕБМАНИЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_webmoney_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ВЕБМАНИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_webmoney_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_xmr',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ МОНЕРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_in_xrp',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ПОПОЛНЕНИЕ РИПЛ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_alfabank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД АЛЬФАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_bch',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД БИТКОИНКЕШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_btc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД БИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_dash',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ДАШ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_etc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ЭФИРКЛАССИК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_eth',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ЭФИР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_gazprombank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ГАЗПРОМБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_ltc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ЛАЙТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_mtsbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД МТСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_otkritie_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ОТКРЫТИЕ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_payeer_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЕЕРЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_payeer_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЕЕРРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_payeer_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЕЕРДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_paypal_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЙПАЛЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_paypal_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЙПАЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_paypal_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_pm_btc',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПМБИТКОИН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_pm_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПМЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_pm_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПМДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_pochtabank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПОЧТАБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_psb_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ПСБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_qiwi_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД КИВИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_qiwi_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД КИВИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_raifaizen_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_rnkb_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РНКБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_roketbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РОКЕТБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_rosbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РОСБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_rosselhoz_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_russtandart_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РУССКИЙСТАНДАРТ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_sberbank_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД СБЕРБАНК'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_skrill_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД СКРИЛЛРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_skrill_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД СКРИЛДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_tinkoff_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ТИНЬКОФФ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_umoney_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ЮМАНИ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_vtb_rub',
            field=models.BooleanField(default=False, max_length=50, verbose_name='АКТИВНОСТЬ НА ВЫВОД ВТБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_webmoney_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ВЕБМАНИЕВРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_webmoney_rub',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ВЕБМАНИРУБ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_webmoney_usd',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_xmr',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД МОНЕРО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_xrp',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД РИПЛ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_alfabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_gazprombank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_mtsbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_otkritie_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_payeer_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_payeer_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_payeer_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_paypal_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_paypal_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_paypal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_pm_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_pm_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_pochtabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_psb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_qiwi_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_qiwi_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_raifaizen_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_rnkb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_roketbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РОКЕТБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_rosbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_rosselhoz_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_russtandart_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_sberbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_skrill_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ СКРИЛЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_skrill_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_tinkoff_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_vtb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=50, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_webmoney_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_webmoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_webmoney_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_in_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ПОПОЛНЕНИЕ РИПЛ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_alfabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_gazprombank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_mtsbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_otkritie_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_payeer_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_payeer_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_payeer_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_paypal_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_paypal_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_paypal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_pm_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_pm_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_pochtabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_psb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_qiwi_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_qiwi_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_raifaizen_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_rnkb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_roketbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РОКЕТБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_rosbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_rosselhoz_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_russtandart_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_sberbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_skrill_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД СКРИЛЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_skrill_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_tinkoff_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_vtb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=50, verbose_name='КОММИСИЯ НА ВЫВОД ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_webmoney_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_webmoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_webmoney_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comis_out_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КОММИСИЯ НА ВЫВОД РИПЛ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_alfabank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_bch',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_btc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_dash',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_etc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_eth',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_gazprombank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_ltc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_mtsbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_otkritie_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_payeer_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_paypal_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_btc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pm_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_pochtabank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_psb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_qiwi_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_qiwi_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_raifaizen_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rnkb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_roketbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РОКЕТБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rosbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_rosselhoz_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_russtandart_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_sberbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_skrill_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ СКРИЛЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_skrill_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_tinkoff_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_umoney_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_vtb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_webmoney_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_alfabank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_bch',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_btc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_dash',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_etc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_eth',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_gazprombank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_ltc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_mtsbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_otkritie_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_payeer_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_payeer_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_payeer_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_paypal_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_paypal_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_paypal_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_pm_btc',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_pm_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_pm_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_pochtabank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_psb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_qiwi_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_qiwi_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_raifaizen_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_rnkb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_roketbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РОКЕТБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_rosbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_rosselhoz_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_russtandart_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_sberbank_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_skrill_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА СКРИЛЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_skrill_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_tinkoff_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_umoney_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_vtb_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_webmoney_eur',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_webmoney_rub',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_webmoney_usd',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_xmr',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_width_xrp',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ВЫВОДА РИПЛ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_xmr',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requsites_xrp',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЕКВИЗИТЫ ДЛЯ ПОПОЛНЕНИЯ РИПЛ'),
        ),
    ]
