# Generated by Django 3.1 on 2020-12-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20201224_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_out_skrill_rub',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_out_skrill_eur',
            field=models.BooleanField(default=False, verbose_name='АКТИВНОСТЬ НА ВЫВОД СКРИЛЛЕВРО'),
        ),
    ]
