# Generated by Django 3.1 on 2020-12-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20201227_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reserv_alfabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ АЛЬФАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_gazprombank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ГАЗПРОМБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_mtsbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ МТСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_otkritie_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ОТКРЫТИЕ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_payeer_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЕЕРЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_payeer_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЕЕРРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_payeer_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЕЕРДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_paypal_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЙПАЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_paypal_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЙПАЛРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_paypal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПАЙПАЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПМБИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pm_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПМЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pm_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПМДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pochtabank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПОЧТАБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_psb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ПСБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_qiwi_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ КИВИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_qiwi_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ КИВИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_raifaizen_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РАЙФАЙЗЕНБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_rnkb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РНКБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_roketbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РОКЕТБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_rosbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РОСБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_rosselhoz_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РОССЕЛЬХОЗБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_russtandart_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РУССКИЙСТАНДАРТ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_sberbank_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ СБЕРБАНК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_skrill_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ СКРИЛЛЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_skrill_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ СКРИЛДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_tinkoff_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ТИНЬКОФФ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_umoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ЮМАНИ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_vtb_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=50, verbose_name='РЕЗЕРВ ВТБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_webmoney_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ВЕБМАНИЕВРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_webmoney_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ВЕБМАНИРУБ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_webmoney_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ ВЕБМАНИДОЛЛАР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='РЕЗЕРВ РИПЛ'),
        ),
    ]
