# Generated by Django 3.1 on 2020-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20201227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reserv_pm_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ ПМБИТКОИН'),
        ),
    ]
