# Generated by Django 3.1 on 2020-12-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20201227_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reserv_bch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ БИТКОИНКЕШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_btc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ БИТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_dash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ ДАШ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_etc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ ЭФИРКЛАССИК'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_eth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ ЭФИР'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_ltc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ ЛАЙТКОИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xmr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ МОНЕРО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reserv_xrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='РЕЗЕРВ РИПЛ'),
        ),
    ]
