# Generated by Django 3.1 on 2020-09-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(db_index=True, max_length=150, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюту',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='TransactionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_transaction', models.CharField(db_index=True, max_length=150, verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Транзакцию',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакцию', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.transactionview', verbose_name='Название транзакции'),
        ),
    ]
