# Generated by Django 3.1 on 2020-09-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20200910_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_status', models.CharField(db_index=True, max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статуса',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.status', verbose_name='Статус'),
        ),
    ]
