# Generated by Django 3.1 on 2020-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20200910_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='transactionview',
            options={'verbose_name': 'Тип транзакции', 'verbose_name_plural': 'Тип транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transactionview',
            name='base_transaction',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Тип транзакции'),
        ),
    ]
