# Generated by Django 3.1 on 2020-09-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20200910_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_sistemchange', models.CharField(db_index=True, max_length=150, verbose_name='Платежная система')),
            ],
            options={
                'verbose_name': 'Платежную систему',
                'verbose_name_plural': 'Платежные системы',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_sistemchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.sistemchange', verbose_name='Платежная система'),
        ),
    ]
