# Generated by Django 3.1 on 2020-09-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20200910_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.transactionview', verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_name',
            field=models.CharField(max_length=150, verbose_name='Название транзакции'),
        ),
    ]
