# Generated by Django 3.1 on 2020-09-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0007_transaction_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_username',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Логин пользователя'),
        ),
    ]
