# Generated by Django 3.1 on 2020-09-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_auto_20200910_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pay.currency', verbose_name='Валюта'),
        ),
    ]
