# Generated by Django 3.1 on 2020-09-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_auto_20200910_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.currency', verbose_name='Валюта'),
        ),
    ]
