# Generated by Django 3.1 on 2020-09-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0010_auto_20200910_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_typechange', models.CharField(db_index=True, max_length=150, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Тип заявок',
            },
        ),
        migrations.CreateModel(
            name='RequestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=150, verbose_name='Название заявки')),
                ('request_sum', models.DecimalField(decimal_places=8, default=0, max_digits=13, verbose_name='Сумма')),
                ('request_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.currency', verbose_name='Валюта')),
                ('request_sistemchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.sistemchange', verbose_name='Платежная система')),
                ('request_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.status', verbose_name='Статус заявки')),
                ('request_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.typechange', verbose_name='Тип заявки')),
                ('request_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Логин пользователя')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
