# Generated by Django 3.1 on 2020-09-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_auto_20200911_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='выполнена', max_length=150, verbose_name='Тип транзакции'),
        ),
        migrations.DeleteModel(
            name='TransactionView',
        ),
    ]
