# Generated by Django 3.1 on 2020-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_auto_20200911_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
