# Generated by Django 3.1 on 2020-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_auto_20200911_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_name',
            field=models.CharField(default='Пополнение кошелька', max_length=150, verbose_name='Название заявки'),
        ),
    ]
