# Generated by Django 3.1 on 2020-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_auto_20200911_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_name',
            field=models.CharField(max_length=150, verbose_name='Название заявки'),
        ),
        migrations.AlterField(
            model_name='requestchange',
            name='request_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
    ]
