# Generated by Django 3.1 on 2020-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0019_auto_20200914_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCBRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('base_currency', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс  валюты')),
            ],
        ),
    ]
