# Generated by Django 3.1 on 2020-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0021_auto_20200915_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='выполнена', max_length=150, verbose_name='Тип транзакции'),
        ),
    ]
