# Generated by Django 3.1 on 2020-09-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0023_auto_20200915_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_userchange',
        ),
    ]
