# Generated by Django 3.1 on 2020-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0024_remove_transaction_transaction_userchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_userchange',
            field=models.CharField(blank=True, max_length=150, verbose_name='Обработчик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=150, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_user',
            field=models.CharField(max_length=150, verbose_name='Логин пользователя'),
        ),
    ]
