# Generated by Django 3.1 on 2020-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0025_auto_20200915_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_criteri', models.CharField(db_index=True, max_length=150, verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
    ]
