# Generated by Django 3.1 on 2020-09-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0026_criterichange'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='criteri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.criterichange', verbose_name='Критерий'),
        ),
    ]
