# Generated by Django 3.1 on 2020-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0027_requestchange_criteri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comis_user', models.CharField(max_length=150, verbose_name='Обработчик')),
                ('valute_usd', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коммисия на обмен USD')),
                ('valute_rub', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коммисия на обмен RUB')),
                ('valute_eur', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коммисия на обмен EUR')),
            ],
            options={
                'verbose_name': 'Коммисию',
                'verbose_name_plural': 'Коммисии',
            },
        ),
    ]
