# Generated by Django 3.1 on 2020-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0028_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='valute_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен EUR'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='valute_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен RUB'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='valute_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия на обмен USD'),
        ),
    ]
