# Generated by Django 3.1 on 2020-09-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0029_auto_20200917_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
