# Generated by Django 3.1 on 2020-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0030_delete_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='date_end_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_end_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
