# Generated by Django 3.1 on 2021-01-04 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCBRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('base_currency', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс  валюты')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='RequestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_userchange', models.CharField(max_length=150, verbose_name='Обработчик заявки')),
                ('date_joined_change', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_end_change', models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('request_name', models.CharField(max_length=150, verbose_name='Номер заявки')),
                ('request_type', models.CharField(max_length=150, verbose_name='Тип заявки')),
                ('request_user', models.CharField(max_length=150, verbose_name='Логин пользователя')),
                ('request_status', models.CharField(max_length=150, verbose_name='Статус заявки')),
                ('request_sum', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Требуемая сумма')),
                ('request_sistemchange', models.CharField(max_length=150, verbose_name='Платежная система')),
                ('criteri', models.CharField(max_length=150, verbose_name='Критерий')),
                ('requisites', models.CharField(max_length=50, verbose_name='Реквизиты')),
                ('request_commission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Комиссия общая')),
                ('request_commission_change', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Комиссия обменника')),
                ('request_good_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма пользователя')),
                ('request_good_sum_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма обменника')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined_change', models.DateTimeField(blank=True, verbose_name='Создана')),
                ('date_end_change', models.DateTimeField(blank=True, verbose_name='Исполнена')),
                ('transaction_name', models.CharField(max_length=150, verbose_name='Название')),
                ('transaction_user', models.CharField(max_length=150, verbose_name='Логин пользователя')),
                ('transaction_status', models.CharField(default='Выполнена', max_length=150, verbose_name='Статус')),
                ('transaction_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('transaction_sistemchange', models.CharField(default='', max_length=150, verbose_name='Платежная система')),
            ],
            options={
                'verbose_name': 'Транзакцию',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_name', models.CharField(max_length=50, verbose_name='Название')),
                ('transfer_out', models.CharField(max_length=50, verbose_name='Отправитель')),
                ('transfer_in', models.CharField(max_length=50, verbose_name='Получатель')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('transfer_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
        ),
    ]
