# Generated by Django 3.1 on 2021-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Сумма'),
        ),
    ]
