# Generated by Django 3.1 on 2021-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0002_auto_20210104_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sistemchange',
            field=models.CharField(max_length=150, verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.CharField(max_length=150, verbose_name='Сумма'),
        ),
    ]
