# Generated by Django 3.1 on 2020-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0002_requestchange_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_type',
            field=models.CharField(max_length=150, verbose_name='Тип заявки'),
        ),
    ]
