# Generated by Django 3.1 on 2020-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0003_auto_20200920_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='requisites',
            field=models.CharField(default='424224242442', max_length=50, verbose_name='Реквизиты'),
        ),
    ]
