# Generated by Django 3.1 on 2021-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0003_auto_20210104_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='date_end_change',
            field=models.DateTimeField(null=True, verbose_name='Дата исполнения'),
        ),
    ]
