# Generated by Django 3.1 on 2020-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0004_requestchange_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='requisites',
            field=models.CharField(max_length=50, verbose_name='Реквизиты'),
        ),
    ]
