# Generated by Django 3.1 on 2020-09-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0005_auto_20200920_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='criteri',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='personalaccount.criterichange', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='requestchange',
            name='request_status',
            field=models.CharField(default='Ожидает оплаты', max_length=150, verbose_name='Статус заявки'),
        ),
    ]
