# Generated by Django 3.1 on 2021-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0006_auto_20210107_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_sum',
            field=models.CharField(max_length=17, verbose_name='Требуемая сумма'),
        ),
    ]
