# Generated by Django 3.1 on 2021-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0007_auto_20210108_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_sum',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Требуемая сумма'),
        ),
    ]
