# Generated by Django 3.1 on 2020-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0008_auto_20200922_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='request_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коммисия'),
        ),
    ]
