# Generated by Django 3.1 on 2021-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0009_auto_20210108_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='request_good_sum_change_valute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма обменника нац валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestchange',
            name='request_good_sum_valute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма пользователя нац валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestchange',
            name='request_sum_valute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Требуемая сумма нац валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestchange',
            name='request_type_valute',
            field=models.CharField(default=0, max_length=50, verbose_name='Тип валюты'),
            preserve_default=False,
        ),
    ]
