# Generated by Django 3.1 on 2020-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0009_requestchange_request_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коммисия'),
        ),
    ]
