# Generated by Django 3.1 on 2020-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0010_auto_20200922_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='request_good_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
