# Generated by Django 3.1 on 2021-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0010_auto_20210108_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default=23, max_length=150, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
