# Generated by Django 3.1 on 2020-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0011_requestchange_request_good_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_good_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
