# Generated by Django 3.1 on 2021-01-10 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0011_transaction_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticDailyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyprofit_user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('dailyprofit_value', models.CharField(max_length=50, verbose_name='Значение')),
                ('dailyprofit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
    ]
