# Generated by Django 3.1 on 2021-01-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0013_auto_20210110_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='request_curse',
            field=models.CharField(default=0, max_length=50, verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
