# Generated by Django 3.1 on 2021-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0014_requestchange_request_curse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycbrf',
            name='base_currency',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс валюты'),
        ),
        migrations.AlterField(
            model_name='requestchange',
            name='request_curse',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс'),
        ),
    ]
