# Generated by Django 3.1 on 2020-09-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0015_auto_20200923_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='date_transfer',
            new_name='transfer_date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='in_transfer',
            new_name='transfer_in',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='name_transfer',
            new_name='transfer_name',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='out_transfer',
            new_name='transfer_out',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='base_currency',
            new_name='transfer_sum',
        ),
    ]
