# Generated by Django 3.1 on 2020-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0016_auto_20200923_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_currency',
            field=models.CharField(default='', max_length=150, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sistemchange',
            field=models.CharField(default='', max_length=150, verbose_name='Платежная система'),
        ),
    ]
