# Generated by Django 3.1 on 2021-01-26 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0016_auto_20210118_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('news_is_publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('news_header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('news_content', models.TextField(max_length=350, verbose_name='Контент')),
                ('news_img', models.ImageField(upload_to='news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
