# Generated by Django 3.1 on 2020-09-28 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0017_auto_20200923_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_userchange',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_joined_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана'),
        ),
    ]
