# Generated by Django 3.1 on 2021-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0018_auto_20210126_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(max_length=800, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_telegram',
            field=models.URLField(default='https://www.telegram.org/', verbose_name='Пост в инстаграме'),
        ),
    ]
