# Generated by Django 3.1 on 2021-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0019_auto_20210130_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=150, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Сумма'),
        ),
    ]
