# Generated by Django 3.1 on 2021-02-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0020_auto_20210214_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_comment',
            field=models.CharField(max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
