# Generated by Django 3.1 on 2021-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0021_transaction_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма'),
        ),
    ]
