# Generated by Django 3.1 on 2021-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0022_auto_20210214_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
    ]
