# Generated by Django 3.1 on 2021-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0023_auto_20210214_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='request_company_profit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Прибыль компании'),
        ),
    ]
