# Generated by Django 3.1 on 2021-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0024_requestchange_request_company_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='request_company_profit',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Прибыль компании'),
        ),
    ]
