# Generated by Django 3.1 on 2021-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0025_auto_20210215_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default=0, max_length=150, verbose_name='Номер транзакции'),
        ),
    ]
