# Generated by Django 3.1 on 2021-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0026_transaction_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_comment',
            field=models.CharField(default='-', max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
