# Generated by Django 3.1 on 2021-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0027_auto_20210218_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchange',
            name='date_change_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
