# Generated by Django 3.1 on 2021-02-25 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0028_requestchange_date_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencycbrf',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
