# Generated by Django 3.1 on 2021-02-25 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0029_currencycbrf_date_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSFormNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ps', models.CharField(max_length=150, verbose_name='')),
                ('user_ps', models.CharField(max_length=150, verbose_name='')),
                ('data_ps', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
            ],
            options={
                'verbose_name': 'Потребность в ПС',
                'verbose_name_plural': 'Потребности в ПС',
            },
        ),
    ]
