# Generated by Django 3.1 on 2021-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalaccount', '0030_psformnow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psformnow',
            name='user_ps',
            field=models.CharField(default='-', max_length=150, verbose_name=''),
        ),
    ]
